/*
 * Kings API
 *
 * This is a sample Kings Server based on the OpenAPI 3.0 specification.
 *
 * API version: 0.1.0
 * Contact: dev.anowak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"flag"
	"log"
	"net/http"

	sw "example/com/nag/kings/go"
)

func main() {
	insecureSSL := flag.Bool("insecure-ssl", false, "Allow certificates from unrecognized CAs")
	flag.Parse()

	log.Println("Server started with flags: insecure-ssl", *insecureSSL)

	// TODO: http to https redirect
	router := sw.NewRouter()

	fs := http.FileServer(http.Dir("./swaggerui"))
	router.PathPrefix("/swaggerui").Handler(http.StripPrefix("/swaggerui/", fs))

	// go http.ListenAndServe(":8080", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	// 	http.Redirect(w, r, "https://"+r.Host+r.URL.String(), http.StatusMovedPermanently)
	// }))
	log.Fatal(http.ListenAndServeTLS(":8081", "./cert/localhost.crt", "./cert/localhost.key", router))
}
