/*
 * Kings API
 *
 * This is a sample Kings Server based on the OpenAPI 3.0 specification.
 *
 * API version: 0.1.0
 * Contact: dev.anowak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	sw "example/com/nag/kings/go"
)

func main() {
	// insecureSSL := flag.Bool("insecure-ssl", false, "Allow certificates from unrecognized CAs")
	// flag.Parse()

	log.Println("Server started")

	// TODO: http to https redirect
	router := sw.NewRouter()

	fs := http.FileServer(http.Dir("./swaggerui"))
	router.PathPrefix("/swaggerui").Handler(http.StripPrefix("/swaggerui/", fs))

	// go http.ListenAndServe(":80", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	// 	http.Redirect(w, r, "https://"+r.Host+r.URL.String()+":443", http.StatusMovedPermanently)
	// }))

	log.Fatal(http.ListenAndServe(":8081", router))
}
